version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/myapp
    environment:
      RAILS_ENV: development
    env_file: ./backend/.env
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000" 
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app_network

  database:
    container_name: postgres
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
